apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: quocub
spec:
  selector:
    matchLabels:
      app: quocub
  replicas: 1
  template:
    metadata:
      labels:
        app: quocub
    spec:
      containers:
      - name: quocub
        image: gogoputtar/quocub
        ports:
        - containerPort: 3000
